
print("Enter group 1 details:")
group1 = (input("name of the group"),input("size of the group: "),input("date of the competition: "),input("Venue of the competition: "),input("type of the medal"))
print("Enter group 2 details:")
group2 = (input("name of the group"),input("size of the group: "),input("date of the competition: "),input("Venue of the competition: "),input("type of the medal"))
print("Enter group 3 details:")
group3 = (input("name of the group"),input("size of the group: "),input("date of the competition: "),input("Venue of the competition: "),input("type of the medal"))
print("Enter group 4 details:")
group4 = (input("name of the group"),input("size of the group: "),input("date of the competition: "),input("Venue of the competition: "),input("type of the medal"))
print("Enter group 5 details:")
group5 = (input("name of the group"),input("size of the group: "),input("date of the competition: "),input("Venue of the competition: "),input("type of the medal"))

print("Group 1 data is", group1)    
print("Group 2 data is", group2)   
print("Group 3 data is", group3)   
print("Group 4 data is", group4)   
print("Group 5 data is", group5)   
